spring:
  application:
    name: streams-demo-app
  datasource:
    # Use FREEPDB1 service name
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: myuser
    password: mypassword
    driver-class-name: oracle.jdbc.OracleDriver
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: streams-demo-app-id
      bootstrap-servers: localhost:9092
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        # Important for handling Debezium timestamps/JSON
        spring.json.trusted.packages: "*"
        # processing.guarantee: exactly_once_v2 # Optional for safer headers

  # Custom properties to define topics
app:
  topics:
    customer: oracle-CUSTOMER
    orders: oracle-ORDERS
    payment: oracle-PAYMENT
    enriched-orders: enriched-orders
    order-paid: events-order_paid
    daily-revenue: analytics-daily_revenue

server:
  port: 8081
